### ISSUE TITLE
Premsql for Javascript.

### ISSUE THREAD

**Issue by ansarizafar** [premAI-io/premsql#19]
Premsql is an amazing project and like LangchainJS and LamaindexJS I would highly recommend releasing a JavaScript version.

**Comment by Anindyadeep** [comment]
Hi, thanks for the comment, well a native js library might not be in our roadmap right now for bandwidth issue. But we will be rolling out our apis which you can self host and then you can use it using js.

**Comment by Anindyadeep** [comment]
Hi just did an early release of PremSQL. Now you can start the PremSQL server and then use it with js axios or whatever language / lib you want. I am closing this issue for now. Reopen this issue or make a different issue if you have question or you encounter any kind of error. Documentations are still not updated. It will be updated soon.
